# Generated by Django 5.1.1 on 2026-06-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Grocery', 'Grocery'), ('Books', 'Books')], default='Electronics', max_length=50),
        ),
    ]
